### ISSUE TITLE
T003-HU001: Habilitar la reproducción de contenido multimedia mediante la vista implementada

### ISSUE THREAD

**Issue by Sudaiii** [lgsilvestre/G4_Metodologia_1_2021#11]

**Comment by festeban11** [comment]
- Se diseñó mockup para la ventana del reproductor - Commit https://github.com/lgsilvestre/G4_Metodologia_1_2021/commit/4446070ff95acc8d97e68c469307d511944341cb
- El diseño se implementó en un archivo fxml de forma parcial y se agregó solo un archivo java para el controlador del reproductor (sin implementación de las funciones) - Commit https://github.com/lgsilvestre/G4_Metodologia_1_2021/commit/5c87d118d5bff5f4949b1405c178e3cf697c929c

**Comment by festeban11** [comment]
- Se puede reproducir contenido en el reproductor, tanto video como audio.
- Se debe tener cuidado con la ruta de los archivos.
- Se ha comentado el codigo - Commit https://github.com/lgsilvestre/G4_Metodologia_1_2021/commit/ceb681680a80bfae6af2a7c103167ad39abe37eb
