### ISSUE TITLE
T001-HU001: Diseñar ventana de reproducción

### ISSUE THREAD

**Issue by Sudaiii** [lgsilvestre/G4_Metodologia_1_2021#14]

**Comment by festeban11** [comment]
- Se diseñó mockup para la ventana del reproductor - Commit https://github.com/lgsilvestre/G4_Metodologia_1_2021/commit/4446070ff95acc8d97e68c469307d511944341cb
- El diseño se implementó en un archivo fxml de forma parcial en las vistas y se agregó un archivo java para el controlador del reproductor (sin implementación de las funciones) - Commit https://github.com/lgsilvestre/G4_Metodologia_1_2021/commit/5c87d118d5bff5f4949b1405c178e3cf697c929c
