### ISSUE TITLE
T001-HU005: Implementar ventana principal

### ISSUE THREAD

**Issue by Sudaiii** [lgsilvestre/G4_Metodologia_1_2021#3]

**Comment by JuanaMontana** [comment]
Se creo en scene builder la ventana principal, y se agregó el pantallainicialcontroller, falta arreglar el código que abre esta ventana, ya que se intentó de diferentes formas pero no se logró resolver este problema

**Comment by JuanaMontana** [comment]
Se resolvió el problema de abrir la ventana inicial al logear un usuario. se agregó el pantallainicialcontroller, falta agregar la funcionalidad de los botones en pantalla

**Comment by JuanaMontana** [comment]
Se implementó la vista de las películas mas nuevas en forma de Banner con movimiento de carrusel.

**Comment by JuanaMontana** [comment]
Se implementó la miniatura de los diferentes menus, lo mas popular, ultimas series agregadas y ultimas peliculas agregadas
