### ISSUE TITLE
T003-HU004: Habilitar la gestion de contenido multimedia mediante la ventana diseñada

### ISSUE THREAD

**Issue by Sudaiii** [lgsilvestre/G4_Metodologia_1_2021#4]

**Comment by matiasenriqueva** [comment]
Se completo la implementación de todo el contenido multimedia (Películas, Música, Series y episodios) por medio de la interfaz de usuario, permite agregar, editar y eliminar los diferentes medios.

Commit Relacionado: 4fdb7833ace53f5b31f1bf407a9aaf9aa84056ca
