### ISSUE TITLE
T002-HU004: Implementar vista de gestion de contenido multimedia

### ISSUE THREAD

**Issue by Sudaiii** [lgsilvestre/G4_Metodologia_1_2021#5]

**Comment by matiasenriqueva** [comment]
En semana 2: se agregaron elementos de navegación de la ventana de gestion multimedia (elementos visuales, retroceso entre páginas).
Agregado un sub menú para agregar películas, falta la implementación completa de la parte lógica. (Faltan varios elementos en este ítem dada a la escasez de tiempo - Se implementara una version mas completa durante el fin de semana siguiente)
Commit Relacionado: 7fe386de97c9eeca2a3491c4561efa4af569d355
